name: Build & Tests

on:
  push:
    branches:
      - '**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup and build .NET
        uses: ./.gitea/actions/step-dotnet-build
        with:
          working-dir: code