name: Push para GitHub

on:
  push:
    branches: [ main ]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Definir Branch
        run: |
          echo "BRANCH=${{ gitea.ref_name }}" >> $GITEA_ENV
          
      - name: Clonar repo do GitHub
        run: |
          git clone https://x-access-token:${{ secrets.GIT_HUB_TOKEN }}@github.com/andrejuck/gw2-item-tracker.git
      
      - name: Checkout da branch correspondente
        run: |
          cd gw2-item-tracker
          git checkout -B "$BRANCH" || git checkout -b "$BRANCH"

      - name: Alterar arquivos
        run: |
          cd gw2-item-tracker
          echo "Atualizado via Gitea em $(date)" >> sync.txt

      - name: Configurar Git
        run: |
          cd gw2-item-tracker
          git config user.name "André Juck Faustino Pereira"
          git config user.email "andrejuck@hotmail.com"

      - name: Commit e push
        run: |
          cd gw2-item-tracker
          git add .
          git commit -m "Sync automático da branch $BRANCH via Gitea" || echo "Nada para commitar na $BRANCH"
          git push origin $BRANCH